### ISSUE TITLE
Unable to find the factory reset file in here

### ISSUE THREAD

**Issue by techman44** [adafruit/Adafruit-ESP32-S3-TFT-Feather-PCB#1]
[README.md](https://github.com/adafruit/Adafruit-ESP32-S3-TFT-Feather-PCB/tree/main/factory-reset#readme)
Factory Reset file - ESP32-S3 TFT Feather

This is the factory reset file for the ESP32-S3 TFT Feather.

But there is no file attached here.

**Comment by scottmc** [comment]
Looks like this was fixed with b9d6e64ff76f12f86c473061b702d037a3398257 ?

**Comment by caternuson** [comment]
Yes it was, along with some other commits to update them. Closing since files are in repo now. Also available here:
https://learn.adafruit.com/adafruit-esp32-s3-tft-feather/factory-reset
