### ISSUE TITLE
The Stemma-QT pinout on the pinout PDF is ambiguous

### ISSUE THREAD

**Issue by DefProc** [adafruit/Adafruit-ESP32-S3-TFT-Feather-PCB#4]
While the colour assignments for the socket are correct, the pinout for the plug as indicated is reversed compared to the socket. 

from: [Adafruit ESP32-S3 TFT Feather Pinout.pdf](https://github.com/adafruit/Adafruit-ESP32-S3-TFT-Feather-PCB/blob/03490c608b28fda5a84814b96e600051c53e8f6a/Adafruit%20ESP32-S3%20TFT%20Feather%20Pinout.pdf)

![image](https://github.com/adafruit/Adafruit-ESP32-S3-TFT-Feather-PCB/assets/343000/1cc8f3f2-866b-4a06-83a3-c9ca4e6c9413)

Ideally, the order of the cable info should be mirrored vertically to match the GND pin 1 of the cable with GND pin 1 of the socket. 

I lost more time than I should have figuring out I made up a cable the wrong way round to an external sensor!

**Comment by caternuson** [comment]
Thanks for pointing this out. The PDF hosted here (see #5), as well as [source SVG hosted on Adafruit Learn](https://learn.adafruit.com/adafruit-esp32-s3-tft-feather/downloads), have been updated.
